# Generated by Django 4.1.6 on 2023-02-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'fuel1',
            },
        ),
    ]
