# Generated by Django 4.1.6 on 2023-02-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_fuel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('write_file_name', models.CharField(default='excell2023', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'upload_file',
                'db_table': 'upload_file',
            },
        ),
    ]
