# Generated by Django 4.1.6 on 2023-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(default='boshqa', max_length=500)),
                ('model_name', models.CharField(default='boshqa', max_length=500)),
                ('body', models.CharField(default='boshqa', max_length=500)),
                ('fuel', models.CharField(default='boshqa', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'vehicle',
                'db_table': 'vehicle',
            },
        ),
    ]
